# Use the official Python 3.12 image
FROM python:3.12-slim

# Set the working directory in the container
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY . /app

# Install any needed packages specified in requirements.txt
RUN pip install --upgrade pip && \
    pip install -r requirements.txt

# Make port 80 available to the world outside this container
EXPOSE 80

# Define environment variable
ENV NAME World

# Run setup_venv.sh to set up the virtual environment and install dependencies
RUN chmod +x setup_venv.sh && ./setup_venv.sh

# Command to run on container start
CMD ["python", "example_usage/create_final_DNA_digital_storage_file/create_dna_digital_storage_file.py", "dna_digital_data_storage/header/header.json", "chunked_data.json", "compressed_data.json", "error_correction_data.json", "proof_of_work.json"]
